main: tacticalaxis.aac.Main
version: 1.0
author: TacticalAxis
name: Auto-Armour Checker
website: https://pixelcubemc.ddns.net/tacticalaxis/
description: Take off a players armour if they put armour on too quickly
commands:
  ac:
    description: Remove a player's armour
